baseURL = 'https://braynm.com'
languageCode = 'en-us'
title = 'Bryan Madrid'
theme = 'novela-fork'
pygmentsstyle = 'monokai'

paginate = 6

[social]
twitter= "https://twitter.com/braynm1925"
github= "https://github.com/braynm"
linkedin= "https://www.linkedin.com/in/braynm"

[taxonomies]
author = "authors"
